- name: create ansible user
  user:
    name: ansible
    system: yes
 
- name: copy sudoers_ansible
  copy:
    src: files/sudoers_ansible
    dest: /etc/sudoers.d/ansible
    owner: root
    group: root
    mode: 0440

- name: copy bashrc
  copy:
    src: files/bashrc
    dest: /home/tege/.bashrc
    owner: tege
    group: tege
    mode: 0644
